### ISSUE TITLE
说明不够完整啊

### ISSUE THREAD

**Issue by yllr78** [levinit/i3wm-config#1]
比如启动配置这块没有，需要安装的软件、字体、theme等部分名称与实际不符，希望完善一下  ：）

---
levinit补充：实际名称不一定是准确的，尤其是theme部分的，某些名字带有git，某些主题有几个版本，你需要的是运用yaourt在aur中搜索关键字下载，比如yaourt numix icons。我只是列出主题的名字供参考。

字体都是看个人喜好的。一般你可以使用文泉驿`pacman -S wqy-microhei`思源黑体：`pacman -S adobe-source-han-sans-otc-fonts`谷歌notofonts`pacman -S noto-fonts-cjk`。

至于软件，必要的几个前面已经列出，其他的软件工具就是个人喜好。

如果你对这些不太熟悉，你可以参考下：http://www.cnblogs.com/unkownarea/p/6472461.html

**Comment by yllr78** [comment]
随机背景那句配置报错，我换成固定背景，运行i3后整个屏幕变成空白，使用win+enter可以出现终端窗口，但是其他的什么都没有。

---
levinit补充：这个是在说明里面有，因为那个wallpaper.sh文件下载下来后是不允许运行的，需要执行下`chmod +x ~/.config/i3/wallpaper.sh`即可。

---
还有我是在vbox虚拟机下用arch，运行xrandr，提示:Can't open display，不知是啥意思。。。

---
levinit补充：
>xrandr命令可以直接向您分别显示系统当前有效输出设备的名称(LVDS或VGA-0等等)和所有有效分辨率。 

虚拟机的显示设备是实体机的显示器，恐怕这个不能设置。（具体不太了解）

**Comment by levinit** [comment]
实际名称不一定是准确，尤其是theme部分的，某些名字带有git，某些主题有几个版本，你需要的是运用yaourt在aur中搜索关键字下载，比如`yaourt numix icons`。我只是列出主题的名字供参考。
字体同理，一般你可以使用文泉驿`pacman -S wqy-microhei`。
至于软件，必要的几个前面已经列出，其他的软件工具就是个人喜好。 
你可以参考下：http://www.cnblogs.com/unkownarea/p/6472461.html
