### ISSUE TITLE
在状态栏显示电量

### ISSUE THREAD

**Issue by Maxwell9669** [levinit/i3wm-config#2]
您好，我用了您的config文件，感觉非常棒，但是在我的电脑上显示的电源的一个图标，没有显示电量的百分比，这样子的话我每次还得用鼠标去看电量的百分比，感觉非常不方便。我看您的那张图片是可以显示电量百分比的，请问您是怎样设置的呢？可以教一下嘛？谢谢

**Comment by levinit** [comment]
试试新的i3block配置文件
5ed52c8a798b834bd235777c7fb0f73b702732f0

**Comment by Maxwell9669** [comment]
好好，谢谢，这次可以显示电量百分比了。
